version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn befriends.app:create_app --host 0.0.0.0 --port 8000 --reload --factory
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run streamlit_chatbot.py
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
